module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    TEACHER: 'TEACHER',
    PARENT: 'PARENT',
  },
  ENQUIRY_STATUS: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    INTERESTED: 'INTERESTED',
    NOT_INTERESTED: 'NOT_INTERESTED',
    FOLLOW_UP: 'FOLLOW_UP',
    CONVERTED: 'CONVERTED',
  },
  STUDENT_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
  },
  FEE_PLAN_TYPE: {
    INSTALLMENT: 'INSTALLMENT',
    MONTHLY: 'MONTHLY',
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PARTIAL: 'PARTIAL',
    PAID: 'PAID',
    OVERDUE: 'OVERDUE',
    FAILED: 'FAILED',
  },
  ANNOUNCEMENT_TYPE: {
    GENERAL: 'GENERAL',
    ACADEMIC: 'ACADEMIC',
    EVENT: 'EVENT',
    HOLIDAY: 'HOLIDAY',
    EMERGENCY: 'EMERGENCY',
  },
  ANNOUNCEMENT_DELIVERY: {
    SENT: 'SENT',
    DELIVERED: 'DELIVERED',
    READ: 'READ',
  },
  ACTIVITY_TYPE: {
    HOMEWORK: 'HOMEWORK',
    CLASS_ACTIVITY: 'CLASS_ACTIVITY',
    PROJECT: 'PROJECT',
  },
  TEACHER_REGISTRATION_STATUS: {
    PENDING: 'PENDING',
    REVIEWED: 'REVIEWED',
    SHORTLISTED: 'SHORTLISTED',
    INTERVIEW: 'INTERVIEW',
    REJECTED: 'REJECTED',
    HIRED: 'HIRED',
  },
  CALENDAR_EVENT_TYPE: {
    HOLIDAY: 'HOLIDAY',
    EVENT: 'EVENT',
    EXAM: 'EXAM',
    ACTIVITY: 'ACTIVITY',
  },
  CLASSES: [
    'Playgroup', 'Nursery', 'LKG', 'UKG',
    'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5',
  ],
  SECTIONS: ['A', 'B', 'C', 'D'],
};
